export const leaderboard = [
    { username: "sandy", level: 27, admin: true },
    { username: "Reivax", level: 27, admin: true },
    { username: "TUTANKHAMUN", level: 26, disqualified: true },
    { username: "11mnv", level: 25, admin: true },
    { username: "velvet.thunder", level: 24, admin: true },
    { username: "sanyaya", level: 24 },
    { username: "vanshsuper", level: 24 },
    { username: "Trick Astley", level: 24 },
    { username: "BHAKTIMEISHAKTI", level: 24, disqualified: true },
    { username: "chunnudada", level: 24, disqualified: true },
    { username: "ramgarhia", level: 23 },
    { username: "totaotaharada", level: 23 },
    { username: "Dipesh Rana", level: 23 },
    { username: "chillsette", level: 23 },
    { username: "Wanheda", level: 23 },
    { username: "kreshi", level: 23 },
    { username: "dca95", level: 22 },
    { username: "abcdefgh", level: 21 },
    { username: "MishuAnubis", level: 20 },
    { username: "iamthedevil", level: 20 },
    { username: "ragesh", level: 20 },
    { username: "SyNdroMe", level: 20 },
    { username: "DMan", level: 19 },
    { username: "MilanoGuy", level: 18 },
    { username: "SeveralSnipe", level: 18 },
    { username: "Surya Sahith", level: 18 },
    { username: "AMRAHS", level: 17 },
    { username: "gambit_Pnav", level: 17 },
    { username: "pxnxxpplxs", level: 17 },
    { username: "Ritz", level: 16 },
    { username: "VoidVampire", level: 16 },
    { username: "Alex.pxh", level: 16 },
    { username: "pancakes", level: 15 },
    { username: "admin", level: 15 },
    { username: "poirot", level: 14 },
    { username: "unweedr", level: 14 },
    { username: "Poltergeist11", level: 14 },
    { username: "ankitamishra", level: 14 },
    { username: "Slayer", level: 14 },
    { username: "CriTMx", level: 14 },
    { username: "DesiBeauty", level: 13 },
    { username: "friedcheese", level: 13 },
    { username: "Srushti khonde", level: 13 },
    { username: "abirami", level: 13 },
    { username: "harshi_842", level: 13 },
    { username: "chillstar", level: 13 },
    { username: "MeenG", level: 13 },
    { username: "thePrnvBot", level: 13 },
    { username: "Aryan", level: 13 },
    { username: "Deepak", level: 13 },
    { username: "abisha_j", level: 13 },
    { username: "fenix", level: 13 },
    { username: "vedanshh_05", level: 13 },
    { username: "eshcapist", level: 13 },
    { username: "ay_123", level: 13 },
    { username: "marshal13", level: 13 },
    { username: "sanchitjain974", level: 13 },
    { username: "Tryharder", level: 12 },
    { username: "swarup_2504", level: 11 },
    { username: "Ishita_agl20", level: 11 },
    { username: "manvi22b7587", level: 11 },
    { username: "Srushti khonde ", level: 11 },
    { username: "SmudgeReturns", level: 11 },
    { username: "sma", level: 10 },
    { username: "yams", level: 10 },
    { username: "coldn00dl3s", level: 10 },
    { username: "ishaneg3215", level: 10 },
    { username: "om_mittal7", level: 9 },
    { username: "Rtt", level: 9 },
    { username: "Kaladin", level: 9 },
    { username: "Sanskriti Das", level: 9 },
    { username: "Shivin Mangal", level: 8 },
    { username: "shubham", level: 8 },
    { username: "yeeshan", level: 8 },
    { username: "adhvaitha_4", level: 8 },
    { username: "Anuvishali", level: 8 },
    { username: "Utkarsh Aryan", level: 8 },
    { username: "anirudh1412", level: 8 },
    { username: "scaa", level: 8 },
    { username: "21bce1486", level: 8 },
    { username: "Kshitij", level: 8 },
    { username: "obu", level: 8 },
    { username: "srev", level: 8 },
    { username: "Vinassh_nreal", level: 8 },
    { username: "ramya", level: 8 },
    { username: "22BEE1165", level: 8 },
    { username: "ShadeLord", level: 6 },
    { username: "Shreyash", level: 6 },
    { username: "cyclonite", level: 6 },
    { username: "endymion", level: 6 },
    { username: "Prateek Chaurasia", level: 6 },
    { username: "vishal", level: 6 },
    { username: "What_if_I_win?", level: 5 },
    { username: "ishitkha1907", level: 4 },
    { username: "THE BOSS", level: 4 },
    { username: "shantaram", level: 4 },
    { username: "Heavenlydevil ", level: 3 },
    { username: "ATAMOTIA", level: 3 },
    { username: "pankajjoshi", level: 3 },
    { username: "Shivam", level: 3 },
    { username: "Srija Nomula", level: 3 },
    { username: "TARUN", level: 3 },
    { username: "Sezoxoq", level: 3 },
    { username: "neyha.13", level: 3 },
    { username: "ShashankPai15", level: 3 },
    { username: "Yathesh#7530", level: 3 },
    { username: "ayushneggi", level: 3 },
    { username: "UWU", level: 3 },
    { username: "Sairajaa", level: 2 },
    { username: "frex", level: 2 },
    { username: "surya#8562", level: 2 },
    { username: "karishma_", level: 2 },
    { username: "om12345", level: 2 },
    { username: "SNV", level: 2 },
    { username: "ty6698@srmist.edu.in", level: 2 },
    { username: "impaiwdiiwt", level: 2 },
    { username: "Chitraksh", level: 2 },
    { username: "21bce1887", level: 2 },
    { username: "Krish", level: 2 },
    { username: "srushti khonde", level: 2 },
    { username: "22BEE1280", level: 1 },
    { username: "22brs1040", level: 1 },
    { username: "22BEE1280 ", level: 1 },
    { username: "22BEC1111", level: 1 },
    { username: "22BEE1316 ", level: 1 },
    { username: "davidsling", level: 1 },
    { username: "Bhyan_160703", level: 1 },
    { username: "a_myth", level: 1 },
    { username: "22BRS124", level: 1 },
    { username: "praneel", level: 1 },
    { username: "Ansul", level: 1 },
    { username: "Alex_Fierro", level: 1 },
    { username: "gonerogue1", level: 1 },
    { username: "22BME1110", level: 1 },
    { username: "Ashmit ", level: 1 },
    { username: "Ishita", level: 1 },
    { username: "22BCE1456", level: 1 },
    { username: "_sashi_here", level: 1 },
    { username: "Lamers", level: 1 },
    { username: "papadivy", level: 1 },
    { username: "baburao", level: 1 },
    { username: "21BRS1385", level: 1 },
    { username: "Adarsh", level: 1 },
    { username: "21BRS1565", level: 1 },
    { username: "Parthav", level: 1 },
    { username: "21BPS1212", level: 1 },
    { username: "21BCE5281", level: 1 },
    { username: "Harsith", level: 1 },
    { username: "Shubhash", level: 1 },
    { username: "Niranchna ", level: 1 },
    { username: "Mohammad Kamran", level: 1 },
    { username: "SilverStone", level: 1 },
    { username: "Chetna ", level: 1 },
    { username: "Parth P M", level: 1 },
    { username: "game_changer_mahi", level: 1 },
    { username: "Pardheev Krishna", level: 1 },
    { username: "loud-af", level: 1 },
    { username: "aayushi", level: 1 },
    { username: "ridha", level: 1 },
    { username: "bismithbabu", level: 1 },
    { username: "Leenasri", level: 1 },
    { username: "Anuragel3501 ", level: 1 },
    { username: "Sanyam Jain", level: 1 },
    { username: "Rishika", level: 1 },
    { username: "AKSHITA", level: 1 },
    { username: "Bittus here", level: 1 },
    { username: "velvet_thunder", level: 1 },
    { username: "karishma", level: 1 },
    { username: "karishma05", level: 1 },
    { username: "Karishma", level: 1 },
    { username: "It's me", level: 1 },
    { username: "Sunmathy", level: 1 },
    { username: "Darshan119", level: 1 },
    { username: "chrisboban", level: 1 },
    { username: "tenar", level: 1 },
    { username: "22bce1278", level: 1 },
    { username: "TONYSTARK", level: 1 },
    { username: "pankajjoshiCVS", level: 1 },
    { username: "prisha_23", level: 1 },
    { username: "Mittalsanchali", level: 1 },
    { username: "BJayant", level: 1 },
    { username: "Cubher", level: 1 },
    { username: "Saniya Firdous", level: 1 },
    { username: "priyanshimoonka ", level: 1 },
    { username: "priyanshi", level: 1 },
    { username: "YUVRAJSINH7775", level: 1 },
    { username: "aditya", level: 1 },
    { username: "Arka Ray", level: 1 },
    { username: "Arshita", level: 1 },
    { username: "ann", level: 1 },
    { username: "ajruttam", level: 1 },
    { username: "khyatis22", level: 1 },
    { username: "Harshvardhan", level: 1 },
    { username: "Shalmali", level: 1 },
    { username: "neganuggets", level: 1 },
    { username: "Surabhi kumari", level: 1 },
    { username: "kriti", level: 1 },
    { username: "mariokartiscool", level: 1 },
    { username: "srishtirgc", level: 1 },
    { username: "chirag", level: 1 },
    { username: "srushti khonde ", level: 1 },
    { username: "drowsycoder", level: 1 },
    { username: "adityagupta37", level: 1 },
    { username: "a_avantika", level: 1 },
    { username: "loluzaka", level: 1 },
    { username: "Shivansh2305", level: 1 },
    { username: "annu", level: 1 },
    { username: "Mandipsah", level: 1 },
    { username: "mandipsah321", level: 1 },
    { username: "mariokart", level: 1 },
    { username: "DEVAN S", level: 1 },
    { username: "Srimathi ", level: 1 },
];
