export const questions = [
    {
        level: 1,
        text: "Good luck, genius",
        image: "https://i.imgur.com/DQ8SOg2.png",
        answer: "brave",
    },
    {
        level: 2,
        text: "Good luck, genius",
        image: "https://i.imgur.com/oFaGki4.png",
        answer: "sputnik",
    },
    {
        level: 3,
        text: "Good luck, genius",
        image: "https://i.imgur.com/gZ0Dre1.png",
        answer: "fcbarcelona",
    },
    {
        level: 4,
        text: "Good luck, genius",
        image: "https://i.imgur.com/v69GpRK.png",
        answer: "jeffbezos",
    },
    {
        level: 5,
        text: "Good luck, genius",
        image: "https://i.imgur.com/bhHtMsG.png",
        answer: "carlpei",
    },
    {
        level: 6,
        text: "Good luck, genius",
        image: "https://i.imgur.com/bjalrwv.png",
        answer: "wanurikahiu",
    },
    {
        level: 7,
        text: "Good luck, genius",
        image: "https://i.imgur.com/TEpvk7f.png",
        answer: "yuvalnoahharari",
    },
    {
        level: 8,
        text: "Good luck, genius",
        image: "https://i.imgur.com/yc6aaRK.png",
        answer: "dassaultrafalejet",
    },
    {
        level: 9,
        text: "Good luck, genius",
        image: "https://i.imgur.com/YRAI5gV.jpeg",
        answer: "deepblue",
    },
    {
        level: 10,
        text: "What was the approximate time when Andy left in 2006?https://en.m.wikipedia.org/wiki/Casino_hotel",
        image: "https://www.shutterstock.com/image-vector/good-luck-hand-lettering-vector-260nw-632212697.jpg",
        answer: "twentyseventeenforty",
    },
    {
        level: 11,
        text: "The Piano Man wants a certain type of girl\nbut that has got a celestial body in a funk. It is \nnot at all the kind of place to raise your kids. \nIt needs to be directed by someone, but even \nhe has homicidal tendencies. He has had his \nfair share of episodes. 3 more of them and it'll \nturn into a whole other show. \nWho'll be the one to rescue them?",
        image: "https://www.shutterstock.com/image-vector/good-luck-hand-lettering-vector-260nw-632212697.jpg",
        answer: "nbc",
    },
    {
        level: 12,
        text: "It was just a scratch Jim, really! Who'd have known! Must be the other half then",
        image: "https://www.shutterstock.com/image-vector/good-luck-hand-lettering-vector-260nw-632212697.jpg",
        answer: "strangerthings",
    },
    {
        level: 13,
        text: "Age cannot wither her, nor custom stale her/infinite variety / Her Amante the principe of the Eternal World / But was it built in a day? / A battle of twins was the price / Nursed in Lupercal by Lupa / Only these impianti can slay that feral!",
        image: "https://www.shutterstock.com/image-vector/good-luck-hand-lettering-vector-260nw-632212697.jpg",
        answer: "aconite",
    },
    {
        level: 14,
        text: "When things were “not great not terrible”, \nthis nation was the first to smell trouble. \nIf you live here, always remember:\n“mxwc laxbb cqn oaxinw bnj” (9)\nOr else be prepared to face the wrath of the ___)",
        image: "https://i.imgur.com/elykdQj.jpeg",
        answer: "stick",
    },
    {
        level: 15,
        text: "She sends a stinger for the hunter, Keep your best foot forward",
        image: "https://imgur.com/JG6S13j",
        answer: "rigel",
    },
    {
        level: 16,
        text: "Mia Thermopolis needs to make an acronym that helps her remember the PIN that opens the next chest. Help her out!",
        image: "https://www.shutterstock.com/image-vector/good-luck-hand-lettering-vector-260nw-632212697.jpg",
        answer: "782450",
    },
    {
        level: 17,
        text: "“Mr. Fahrenheit wouldve been x years old today. Calling the UK, it all adds up...The year when Tallica, Axl, Ziggy Stardust, the careless whisperer and you too came together for him, pretty much sums it up.”",
        image: "https://www.shutterstock.com/image-vector/good-luck-hand-lettering-vector-260nw-632212697.jpg",
        answer: "2112",
    },
    {
        level: 18,
        text: "“Its about judicandus homo and reus, but… humanity has ended” which style would you prefer?",
        image: "https://i.imgur.com/60IzzdL.jpeg",
        answer: "swiss",
    },
    {
        level: 19,
        text: "XX in Rome?",
        image: "https://i.imgur.com/2YFhvhy.png",
        answer: "lxvi",
    },
    {
        level: 20,
        text: "suspect no. 3301\nYoull find the answer @ the sample - the person behind this man",
        image: "https://i.imgur.com/FuL0Iha.jpeg",
        answer: "iamhilluminated",
    },
    {
        level: 21,
        text: "40.856802192541245, -96.78332382785781\nHe who prevailed was a little one, but the \nmiddle of his name turns out to be as high as \nx metres.\nYou’ll find it in the group of stars called __",
        image: "https://i.imgur.com/cWu1l8r.jpeg",
        answer: "pavo",
    },
    {
        level: 22,
        text: 'The day we landed on the moon, has a best friend. search for "me" amongst those few people',
        image: "https://i.imgur.com/hnVzh2g.jpeg",
        answer: "centimillimental",
    },
    {
        level: 23,
        text: "Gods and Kings in the boden bunker, seek a weapon, \nfollow /n/dfqPRxW for a short stay in hell.\nIf you have a question, return to square one,\nremember what you learn here, good luck and farewell.",
        image: "https://www.shutterstock.com/image-vector/good-luck-hand-lettering-vector-260nw-632212697.jpg",
        answer: "v",
    },
    {
        level: 24,
        text: "FiY1BIZL#dYZJ0ifBVw7no8Y0HdTgiw",
        image: "https://www.tenforums.com/geek/gars/images/2/types/thumb_14486407500Folder.png",
        answer: "sonofsam",
    },
    {
        level: 25,
        text: "1n6ygxvHkpNjazoYu_hntQRpJyo80IPk0",
        image: "https://cdn.discordapp.com/attachments/844641492646625340/1109824602550567013/monke.png",
        answer: "LYeGOChNICA30165422",
    },
    {
        level: 26,
        text: "Troy & Abed in the morning, heard sounds of a jail door slamming shut, a hammer hitting an anvil \nand some different drum noises.\n\nuse the code to help them out",
        image: "https://i.imgur.com/tsA0Ahy.jpeg",
        answer: "stephenking",
    },
];
